In [1]:
import numpy as np

In [3]:
R=np.random.randn(10,5)

In [7]:
A=np.matmul(R,R.T)
A.shape

(10, 10)

In [8]:
evd=np.linalg.svd(A)

In [10]:
type(evd)

tuple

In [11]:
len(evd)

3

In [18]:
evd[1]

array([2.08956761e+01, 1.17476486e+01, 9.05367189e+00, 2.98431961e+00,
       2.34238133e+00, 1.35133180e-15, 1.11084473e-15, 6.77300832e-16,
       3.28288809e-16, 2.23359971e-17])

In [19]:
np.linalg.norm(evd[0],axis=0,ord=2)
#thus all are unit vectors.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
#to see whether all vectors are at angle of 90 degree. vertical direction
np.linalg.norm(evd[2],axis=1,ord=2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
q1_transpose=evd[2][0,:]
q1_transpose

array([-0.07257685, -0.30345059, -0.14642864, -0.57628974, -0.23848803,
       -0.03599713, -0.356722  , -0.58684813, -0.09534359,  0.10097066])

In [26]:
evd[2]

array([[-0.07257685, -0.30345059, -0.14642864, -0.57628974, -0.23848803,
        -0.03599713, -0.356722  , -0.58684813, -0.09534359,  0.10097066],
       [ 0.24848373, -0.1753412 , -0.68490146,  0.13480172, -0.44929413,
        -0.01480693,  0.16549517,  0.11510802,  0.42114894,  0.01266412],
       [-0.37455345,  0.27499696, -0.37031242,  0.38356512,  0.16183882,
        -0.20708317, -0.10602438, -0.44207948, -0.04748682, -0.47098537],
       [ 0.38843715,  0.06964576, -0.33414748, -0.47073096,  0.60473149,
        -0.20891371,  0.23935264,  0.05963012, -0.05967732, -0.19305942],
       [-0.09964397,  0.42411812,  0.07702676, -0.14591522, -0.3353888 ,
        -0.65167089,  0.37032156, -0.06132825, -0.11128148,  0.30418277],
       [-0.10842198,  0.01232325,  0.22735474, -0.0399621 ,  0.19931329,
         0.22936873,  0.47934394, -0.47435906,  0.60984048,  0.12560779],
       [-0.30649236,  0.58079522, -0.24329135, -0.29186639,  0.09155122,
         0.26528271, -0.35579034,  0.24682167

In [30]:
q1_transpose=q1_transpose.reshape(1,q1_transpose.shape[0])
q1_transpose
#convert into row vector.

array([[-0.07257685, -0.30345059, -0.14642864, -0.57628974, -0.23848803,
        -0.03599713, -0.356722  , -0.58684813, -0.09534359,  0.10097066]])

In [31]:
np.matmul(q1_transpose,evd[0])

array([[ 1.00000000e+00, -2.02419541e-17,  1.03622676e-16,
        -2.61344778e-16, -1.20936995e-16,  7.75145551e-17,
         1.09340347e-16, -7.19145482e-18, -1.01472811e-16,
        -2.87101550e-17]])